version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: '05:00'
      timezone: UTC
    open-pull-requests-limit: 5
    commit-message:
      prefix: deps
      include: scope
    labels:
      - dependencies
      - javascript
    groups:
      all-npm-deps:
        patterns:
          - '*'
        update-types:
          - minor
          - patch

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: '05:00'
      timezone: UTC
    open-pull-requests-limit: 5
    commit-message:
      prefix: ci
      include: scope
    labels:
      - dependencies
      - github-actions
    groups:
      all-github-actions:
        patterns:
          - '*'
        update-types:
          - minor
          - patch
